### PR TITLE
TDD project

### PR DESCRIPTION
**Pull request by fmanimashaun**
# Test-Driven Development (TDD) Project

## Description

This pull request introduces the implementation of a `Solver` class with methods for calculating factorials, reversing strings, and solving the FizzBuzz problem. The unique aspect of this project is that it follows the principles of Test-Driven Development (TDD), meaning that tests were written before the code.

## Changes

- Implemented the `Solver` class with methods `factorial`, `reverse`, and `fizzbuzz`.
- Added comprehensive unit tests for all methods in the `Solver` class.
- Ensured that all tests are passing and the code coverage is maximized.

### CODE REVIEW

**Review by prolajumokeoni — COMMENTED** [review]
Hi @fmanimashaun 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that shows coauthored commits instead of individual commits, it will be better if  each partner has individual commits in this pair programming project  👍🏿 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Alusp — CHANGES_REQUESTED** [review]
Hi @Ademola-coding and @prolajumokeoni , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
close

## Highlights
- [ ] Use Professional Readme file 👍
- [ ] Descriptive PR Summary used 👍
- [ ] Write unit tests using Rspec.👍


## Required Changes ♻️
_Check the comments under the review._

- [ ] Good job so far, :clap:, however, according to the project requirement, your Commit history sequence should clearly show that each of the Solver class methods were tested before writing the code. Please resolve that. :slightly_smiling_face: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by abdulhamiid — APPROVED** [review]
# :green_circle:  Approved! :partying_face:
Hi Tean 👋, 
image
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 🌟

- ✔️ Write unit tests using Rspec.
- ✔️ Write Rspec unit tests with mocks.
- ✔️ Understand the TDD concept.

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by nicupop729** [comment]
@Alusp please note that @Ademola-coding only pushed false commits without a real code contribution.

As mentioned in the announcement channel, please invalidate if the students have co-authored commits. Please also check the contribution of the pair-programming partners, and invalidate if real code contribution is missing.

**Comment by Apatakiti** [comment]
Base on our work distribution for the week,  this is his part, that's why he made majority of the commit.

Should I work on the project again myself and request a re-review @nicupop729

**Pull request merged**
